# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql
  
  mysql:
    image: mysql:8.0.23
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employee_db
